### ISSUE TITLE
Weird error in combination with dplyr::rowwise / df grouped by row

### ISSUE THREAD

**Issue by srenatus** [mtennekes/treemap#14]
Hi,

The following behaviour confused me a lot today (maybe just for future reference)

```R
> library(dplyr)
> library(treemap)
> df <- data.frame(x=1:2, y=3:4, z=c("foo", "bar"))
> treemap(df, index="z", vSize="x", type="index") # all good!

> df <- df %>% rowwise %>% mutate(y = x+y) # for this example only
> df
Source: local data frame [2 x 3]
Groups: <by row>

  x y   z
1 1 4 foo
2 2 6 bar
> class(df)
[1] "rowwise_df" "tbl_df"     "tbl"        "data.frame"
> treemap(df, index="z", vSize="x", type="index")
Error in `:=`(vColor.temp, 1) : 
  Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").
> ungroup(df) %>% treemap(index="z", vSize="x", type="index") # all good!
```

I don't suggest that treemap does the ungroup'ing, but I'd not have expected it to be that harmful ;)

Thanks for the great library :)

**Comment by mtennekes** [comment]
Hi Stephan,

Seems like dplyr and data.table bite each other:

 > df <- data.frame(x=1:2, y=3:4, z=c("foo", "bar"))
 > class(df)
[1] "data.frame"
 > df <- df %>% rowwise %>% mutate(y = x+y) # for this example only
 > class(df)
[1] "rowwise_df" "tbl_df"     "tbl"        "data.frame"
 > dfDT <- as.data.table(df)
 > class(dfDT)
[1] "rowwise_df" "tbl_df"     "tbl"        "data.table" "data.frame"

I will have a look at it, a good reason for me to learn dplyr:)

Best,
Martijn

**Comment by mtennekes** [comment]
dplyr works now!

**Comment by srenatus** [comment]
Thanks @mtennekes :)
