### ISSUE TITLE
javascript library

### ISSUE THREAD

**Issue by timelyportfolio** [mtennekes/treemap#16]
I saw in the presentation that a Javascript library was "in the near future".  I would love to contribute if you have something started.  Thanks for all your packages.

**Comment by mtennekes** [comment]
Thanks!

Someone else has taken initiative for a JS implementation, see [https://github.com/e-/TreeColors.js]
I don't know that the status is, but surely any contribution could be welcome. Note that is it only the TreeColors part of the treemap package.

**Comment by timelyportfolio** [comment]
Great, thanks.  I'll follow that.  I also saw the sunburst in the paper.  There is no code though in the package to create that, correct?  I have converted before, but wondered if your function is better than mine.

**Comment by mtennekes** [comment]
It's here: [https://github.com/mtennekes/hierCols/tree/master/paperVisweek2014/sunburst]
