### ISSUE TITLE
itreemap - incorrect initial state of "vColor" variable

### ISSUE THREAD

**Issue by mlitzkow** [mtennekes/treemap#21]
For some simple datasets the value given for "vColor" in the call to itreemap() seems to be ignored.  I posted an example to  StackOverflow, but nobody was able to solve the issue.  Note that it is possible to use the interface to set the vColor variable as desired, the only problem is that the initial state of the interactive treemap is not as specified.  The stackoverflow post is at

>[stackoverflow post](http://stackoverflow.com/questions/31746344/r-treemap-vcolor-parameter)

**Comment by mtennekes** [comment]
Fixed. If you like, you can install the latest version: `devtools::install_github("treemap", username="mtennekes", subdir="pkg")`.
