### ISSUE TITLE
treemap/test/shiny.R does not work

### ISSUE THREAD

**Issue by martinjhnhadley** [mtennekes/treemap#22]
The shiny.R test file reports:

Error in .func() : could not find function "tmLocate"

I installed the package using `install_github` rather than from CRAN and the repo still includes a tmLocate.R definition and `ls(getNamespace("treemap"), all.names=TRUE)` confirms the function is there.

Note: There's also a warning that `hoverID` has been deprecated in `shiny` and that `hover` is now sufficient.

**Comment by mtennekes** [comment]
I only use the test folder for prototype testing scripts. Sorry for the misleading name.
The final version of the shiny app is `itreemap()`

**Comment by martinjhnhadley** [comment]
Thanks for reply, understand now. In the near future I will be ripping apart itreemap to get a minimally interactive version of a treemap for a single dataset.

**Comment by timelyportfolio** [comment]
@martinjhnhadley perhaps you might be interested in [`d3treeR`](https://github.com/timelyportfolio/d3treeR) which converts a `treemap` to an interactive `d3.js` treemap.  See post [Week 29 | d3treeR v2](http://www.buildingwidgets.com/blog/2015/7/22/week-29-d3treer-v2) for a thorough discussion.

If you do like it or use it, I would love your feedback, comments, suggestions.

**Comment by martinjhnhadley** [comment]
@timelyportfolio many thanks for this, it's going to be a great solution to another problem that I have.

My current needs are quite simple though, and are being met by using the `tmLocate` function in the `treemap` package. All I'd like to do is have a flat `treemap` that the user can click on to expose information about the rectangle they have clicked.

May I ask the design decision behind not exporting `tmLocate` and it's brethren as publically available functions/arguments for the `treemap` function? The logic you have within `getClickID` is very nice.
