### ISSUE TITLE
warning on CRAN

### ISSUE THREAD

**Issue by vijaybarve** [mtennekes/treemap#28]
`
Version: 2.4 
Check: whether package can be installed 
Result: WARN 
    Found the following significant warnings:
     Warning: replacing previous import by ‘grid::arrow’ when loading ‘treemap’
     Warning: replacing previous import by ‘grid::unit’ when loading ‘treemap’ 
Flavors: r-release-linux-x86_64, r-oldrel-windows-ix86+x86_64
`

**Comment by mtennekes** [comment]
Tnx for reporting this! Should be fixed now.

**Comment by vijaybarve** [comment]
The warning is still there 

https://cran.r-project.org/web/checks/check_results_treemap.html

**Comment by mtennekes** [comment]
I know, I still have to submit this version to CRAN;-)

**Comment by mtennekes** [comment]
In addition: this warning should have no influence on the functionality of `treemap`: it is a conflict between `grid` and `ggplot2`, where `ggplot2` re-exports the objects `arrow` and `unit` from `grid`. I managed the  imports better to prevent this warning, but I'll wait with a new package update until there is more reason to update.

**Comment by vijaybarve** [comment]
Thanks for the explanation, now I understand the problem better. Since I use `treemap` in my package `bdvis` I too get that warning, and before submitting next version to CRAN I wanted to make sure I am handling that properly.
