### ISSUE TITLE
Categorical treemap in R does not show all the categories

### ISSUE THREAD

**Issue by fissehab** [mtennekes/treemap#34]
I was playing with treemaps in R and when I try categorical treemap, the treemap shows only one category. I wanted to reproduce treemap [examples](https://onlinehelp.tableau.com/current/pro/desktop/en-us/buildexamples_treemap.html) in Tableau but the categorical example is not giving me a correct treemap. The data is public and it is from Tableau website. It can be downloaded from[ here]. The treemap below shows only one category but the data has four categories. 
(https://community.tableau.com/servlet/JiveServlet/downloadBody/1236-102-1-1149/Sample%20-%20Superstore%20Sales%20(Excel).xls).
`library(readxl)

library(dplyr)

Sample_Superstore <- read_excel("Sample_Superstore.xls")

grouped=Sample_Superstore%>%select(`Sub-Category`,Sales,`Ship Mode`)%>%
           group_by(`Sub-Category`,`Ship Mode`)%>%summarise(Total_Sales=sum(Sales))

treemap(grouped, 
 index="Sub-Category", 
 vSize="Total_Sales",  
 vColor="Ship Mode",
 type="categorical"
)`

**Comment by mtennekes** [comment]
I only see three categories of ShipMode:

    > table(Sample_Superstore$ShipMode)
    Delivery Truck    Express Air    Regular Air 
              1146            983           6270 

Notice that Tableau not only aggregates the tiles by SubCategory, but also by ShipMode itself (as main category). Without doing this, each subcategory is assigned to one (arbitrarily chosen) category.

This should work:

    treemap(grouped,
            index=c("ShipMode", "SubCategory"),
            vSize="Total_Sales",
            vColor="ShipMode",
            type="categorical"
    )

I'll have to fix the `data.table` warning though

**Comment by fissehab** [comment]
Thanks for the prompt reply. I actually put a wrong link for the data.

This is the correct  link and the "Ship Mode" has four categories: 'Second Class' 'Standard Class' 'First Class' 'Same Day'. However, the treemap shows only 'First Class' .
https://community.tableau.com/servlet/JiveServlet/download/351988-57774/Sample%20-%20Superstore.xls

**Comment by mtennekes** [comment]
My code also works for this one:

![rplot](https://cloud.githubusercontent.com/assets/2444081/21853620/2a127ebc-d818-11e6-9743-38f3aa3de8d1.png)

You can use `fontsize.labels` to omit the labels of ShipMode in the treemap itself.

**Comment by fissehab** [comment]
Thank you!
