### ISSUE TITLE
Bug for legend

### ISSUE THREAD

**Issue by ugroempi** [mtennekes/treemap#43]
Hi Martijn,

I find that the legend to treemap shows wrong labels under some circumstances, see the following code:

`data("GNI2014")`
`GNI2014sort <- GNI2014`
`GNI2014sort$contnum <- as.numeric(GNI2014sort$continent)`
`## legend OK for the following call`
`treemap(GNI2014sort, "iso3", "population", `
`        algorithm="pivotSize", vColor="contnum", type="value")`
`## legend not OK for the following call`
`treemap(GNI2014sort, "continent", "population", `
`        algorithm="pivotSize", vColor="contnum", type="value")`

In the second call, the labels shown are 20 times the actual values (which are 1 to 8). (Of course, this is a situation in which one would better suppress the legend altogether, but nevertheless the values shown should be correct.)

Best, Ulrike

**Comment by mtennekes** [comment]
Hi Ulrike,

I think it is correct. The default aggregation function for numeric data is sum, so it just sums all the values. You can change this as follows:

```
treemap(GNI2014sort, "continent", "population",
        algorithm="pivotSize", vColor="contnum", type="value", fun.aggregate = "mean")
```
