### ISSUE TITLE
Warning message when using type="color", not solved in version 2.4-2

### ISSUE THREAD

**Issue by vuleniac** [mtennekes/treemap#46]
This issue was said to be fixed in version 2.4-2. It is not. This is NOT related to issue #34.

There is a data.table warning message when using type = color. Reproducible example:

mtcars %>% head %>% 
   mutate(color = "red") %>% 
   treemap(index = "cyl", vSize = "cyl", vColor = "color", type = "color")

Warning message:
In `[.data.table`(dtfDT, , `:=`("c", fact), with = FALSE) :
  with=FALSE ignored, it isn't needed when using :=. See ?':=' for examples.

The issue impairs the use of d3Tree with treemaps

**Comment by mtennekes** [comment]
A bit late to reply ;-) but I don't get this warning anymore. Seems to be fixed...
