### ISSUE TITLE
Legend Reverse Order

### ISSUE THREAD

**Issue by dalekube** [mtennekes/treemap#48]
I am using treemap in a Shiny app using the following parameters:

type="dens"
algorithm="pivotSize"
sortID="-size"

The rectangles in the treemap are ordered by size from left to right with the biggest rectangles on the left. However, the legend is shown from right to left with the largest index values show on the right side of the scale. I would like to reverse the order of the legend so the scale aligns to the treemap.

I don't see any existing method for accomplishing this. Am I overlooking something?

**Comment by GiGAntia1** [comment]
hello there
