### ISSUE TITLE
update CRAN package

### ISSUE THREAD

**Issue by ssayols** [mtennekes/treemap#52]
Dear Martijn,
Do you plan to add the changes in commit  #49 into CRAN?
Currently, strict build systems like the one used in Bioconductor will fail the checks for packages using the `treemap` function as it is now in CRAN.

cheers,
Sergi

**Comment by mtennekes** [comment]
Will submit a new version soon

**Comment by mtennekes** [comment]
Done: treemap 2.4-3 on its way to CRAN.
