### ISSUE TITLE
Caption Argument

### ISSUE THREAD

**Issue by msgoussi** [mtennekes/treemap#56]
Hi... 
I am wondering if treemap function can accept caption argument!

**Comment by msgoussi** [comment]
I wish there is a caption argument so i could add the source of the data used
![image](https://github.com/mtennekes/treemap/assets/18138496/13fcddb1-6bd4-4b13-94e9-e64ea76aff09)

**Comment by mtennekes** [comment]
You can easily do this with adding text via the grid package:

```r
treemap(GNI2014, index=c("continent", "iso3"), vSize = "population")
grid::grid.text(x = 0.05, y = 0.05, "Source: ABC", just = "left")
```

Hope that helps

**Comment by msgoussi** [comment]
I have a little problem, if i export the map to pdf, the caption will not below the chart.
```
library(treemap)
data(GNI2014)
Cairo::CairoPDF(file = "test.pdf", 
                width = 10, height = 10)
treemap(GNI2014, index=c("continent", "iso3"), vSize = "population")
grid::grid.text(x = 0.05, y = 0.05, "Source: ABC", just = "left")
dev.off()
```
![image](https://github.com/mtennekes/treemap/assets/18138496/f5655292-85c6-4f5e-9f8c-31e46e32167e)

Please advise if you can.

**Comment by mtennekes** [comment]
`treemap` takes the argument `vp`, which you can use to specify the viewport for the treemap (with grid::viewport):

```r
treemap(GNI2014, index=c("continent", "iso3"), vSize = "population", vp = grid::viewport(y = .6, height = .8))
grid::grid.text(x = 0.05, y = 0.05, "Source: ABC", just = "left")
```
